

import java.sql.*;
import javax.swing.JOptionPane;



/**
 *
 * @author hs247
 */
public class Chococake extends javax.swing.JFrame {

    Connection con;
       ResultSet rs;
       PreparedStatement pst;
    public Chococake() {
        initComponents();
        con = dbconnect.ConnecrDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        backBtn = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        egglessRB = new javax.swing.JRadioButton();
        eggRB = new javax.swing.JRadioButton();
        quantityCBox = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        buyBtn = new javax.swing.JButton();
        totalBtn = new javax.swing.JButton();
        totalTF = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel19 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 530));
        setPreferredSize(new java.awt.Dimension(901, 531));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 36)); // NOI18N
        jLabel1.setText("Chocolate Cake");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(70, 30, 256, 39);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\java project\\Bakery management system\\image\\Chocolate Cake.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(100, 170, 150, 130);

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel3.setText("NAME");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 111, 58, 30);

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel5.setText("TYPE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(370, 147, 46, 30);

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel6.setText("PRICE (per cake)");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(370, 221, 140, 30);

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel7.setText("QUANTITY");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 183, 94, 30);

        backBtn.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        backBtn.setText("BACK");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });
        getContentPane().add(backBtn);
        backBtn.setBounds(640, 40, 80, 30);

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel1.setLayout(null);

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel13.setText(" ₹1000.00(eggless) and ₹1200.00(egg)");
        jPanel1.add(jLabel13);
        jLabel13.setBounds(160, 131, 275, 30);

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel4.setText("Chocolate cake");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(160, 21, 110, 30);

        buttonGroup1.add(egglessRB);
        egglessRB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        egglessRB.setText("Eggless");
        jPanel1.add(egglessRB);
        egglessRB.setBounds(160, 61, 69, 25);

        buttonGroup1.add(eggRB);
        eggRB.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        eggRB.setText("Egg");
        jPanel1.add(eggRB);
        eggRB.setBounds(247, 58, 47, 30);

        quantityCBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "1", "2", "3", " " }));
        jPanel1.add(quantityCBox);
        quantityCBox.setBounds(160, 95, 85, 30);

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel11.setText("1 Kg");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(160, 169, 73, 22);

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel12.setText("7-8 Persons");
        jPanel1.add(jLabel12);
        jLabel12.setBounds(160, 205, 120, 22);

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel14.setText("<html>3 layers of moist, dense chocolate cake filled with a dark chocolate butter cream and topped with a chocolate ganache and truffles. This cake is perfect for chocolate lover.</html>");
        jPanel1.add(jLabel14);
        jLabel14.setBounds(160, 237, 260, 90);

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel8.setText("WEIGHT");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(12, 165, 74, 30);

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel9.setText("SERVES");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(12, 201, 68, 30);

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel10.setText("DESCRIPTION");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(12, 237, 123, 30);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(360, 90, 450, 340);

        buyBtn.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        buyBtn.setText("BUY");
        buyBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buyBtnActionPerformed(evt);
            }
        });
        getContentPane().add(buyBtn);
        buyBtn.setBounds(650, 440, 80, 30);

        totalBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        totalBtn.setText("TOTAL");
        totalBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalBtnActionPerformed(evt);
            }
        });
        getContentPane().add(totalBtn);
        totalBtn.setBounds(60, 390, 100, 31);
        getContentPane().add(totalTF);
        totalTF.setBounds(200, 390, 80, 30);

        jLabel15.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel15.setText("PRODUCTID :");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(50, 110, 130, 22);

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jLabel16.setText("cake01");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(180, 110, 70, 20);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 100, 200, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon("E:\\java project\\Bakery management system\\image\\surface.jpg")); // NOI18N
        jLabel19.setText("jLabel19");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(0, 0, 900, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed
       new Cakes().setVisible(true);
       dispose();
    }//GEN-LAST:event_backBtnActionPerformed

    private void buyBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buyBtnActionPerformed
           String sql = "insert into Orderinfo(ProductID,Name,Type,Quantity,TotalAmount) values(?,?,?,?,?)";
           try
        {
          pst=con.prepareStatement(sql);
          pst.setString(1,"cake01");
          pst.setString(2," Chocolate cake");
          egglessRB.setActionCommand("Eggless");
          eggRB.setActionCommand("Egg");
          pst.setString(3,buttonGroup1.getSelection().getActionCommand());
          pst.setString(4,(String)quantityCBox.getSelectedItem());
          pst.setString(5,totalTF.getText());
          pst.execute();
          JOptionPane.showMessageDialog(null,"order insert");
         
          Shipping s = new Shipping();
          s.setVisible(true);
          dispose();
        }
      catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }       
    }//GEN-LAST:event_buyBtnActionPerformed

    private void totalBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalBtnActionPerformed
        double t;
        if(egglessRB.isSelected())
        { if (quantityCBox.getSelectedItem().equals("1"))
          { t=1000.00;  }
          else
            if(quantityCBox.getSelectedItem().equals("2"))
            { t=1000.00*2;  }
            else
              t=1000.00*3;
        }       
        
        else
        {
          if(quantityCBox.getSelectedItem().equals("1"))  
          { t=1200.00;  }
          else
             if (quantityCBox.getSelectedItem().equals("2"))
             { t=1200.00*2;  }
             else 
                 t=1200.00*3;
        }
        totalTF.setText(Double.toString(t));
        t=Double.parseDouble(totalTF.getText());
    }//GEN-LAST:event_totalBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Chococake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Chococake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Chococake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Chococake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Chococake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton buyBtn;
    private javax.swing.JRadioButton eggRB;
    private javax.swing.JRadioButton egglessRB;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> quantityCBox;
    private javax.swing.JButton totalBtn;
    private javax.swing.JTextField totalTF;
    // End of variables declaration//GEN-END:variables
}
