/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
import java.sql.*;
import net.proteanit.sql.DbUtils;

public class Details extends javax.swing.JFrame {

    Connection con = null;
    ResultSet rs= null;
    PreparedStatement pst = null;
    public Details() {
        con = dbconnect.ConnecrDB();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Orders = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        infotable = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        msgtable = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        ordertable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 530));
        setPreferredSize(new java.awt.Dimension(910, 550));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 530));
        getContentPane().setLayout(null);

        Orders.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        Orders.setPreferredSize(new java.awt.Dimension(870, 470));

        jPanel1.setMaximumSize(new java.awt.Dimension(732, 455));
        jPanel1.setLayout(null);

        infotable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "UserID", "Name", "Email", "Password", "Gender", "Mobile", "State", "Full address"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        infotable.setCellSelectionEnabled(true);
        jScrollPane1.setViewportView(infotable);
        infotable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(10, 60, 840, 190);

        jButton1.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButton1.setText("GET DETAILS");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(400, 290, 140, 29);

        jLabel3.setFont(new java.awt.Font("Perpetua", 1, 24)); // NOI18N
        jLabel3.setText("DETAILS");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(30, 20, 130, 28);

        jLabel1.setIcon(new javax.swing.ImageIcon("E:\\java project\\Bakery management system\\image\\cupcake.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(-6, 0, 870, 440);

        Orders.addTab("Customer Details", jPanel1);

        jPanel3.setPreferredSize(new java.awt.Dimension(875, 460));
        jPanel3.setLayout(null);

        msgtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Name", "Email", "Mobile no.", "Subject ", "Message"
            }
        ));
        jScrollPane3.setViewportView(msgtable);
        if (msgtable.getColumnModel().getColumnCount() > 0) {
            msgtable.getColumnModel().getColumn(2).setResizable(false);
            msgtable.getColumnModel().getColumn(2).setPreferredWidth(20);
            msgtable.getColumnModel().getColumn(3).setPreferredWidth(20);
        }

        jPanel3.add(jScrollPane3);
        jScrollPane3.setBounds(10, 10, 840, 160);

        jButton2.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButton2.setText("GET MESSAGES");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton2);
        jButton2.setBounds(360, 260, 160, 29);

        jLabel2.setIcon(new javax.swing.ImageIcon("E:\\java project\\Bakery management system\\image\\51528535-herbs-and-spices-over-wood-background-top-view-with-copy-space.jpg")); // NOI18N
        jLabel2.setText("jLabel2");
        jPanel3.add(jLabel2);
        jLabel2.setBounds(0, 0, 860, 440);
        jPanel3.add(jPanel2);
        jPanel2.setBounds(180, -20, 10, 10);

        Orders.addTab("Messages", jPanel3);

        jPanel4.setLayout(null);

        ordertable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Product ID", "Product Name", "Type", "Quantity", "Total Amount"
            }
        ));
        jScrollPane4.setViewportView(ordertable);
        if (ordertable.getColumnModel().getColumnCount() > 0) {
            ordertable.getColumnModel().getColumn(0).setResizable(false);
            ordertable.getColumnModel().getColumn(0).setPreferredWidth(5);
            ordertable.getColumnModel().getColumn(1).setPreferredWidth(80);
            ordertable.getColumnModel().getColumn(2).setResizable(false);
            ordertable.getColumnModel().getColumn(2).setPreferredWidth(5);
            ordertable.getColumnModel().getColumn(3).setPreferredWidth(5);
            ordertable.getColumnModel().getColumn(4).setPreferredWidth(20);
        }

        jPanel4.add(jScrollPane4);
        jScrollPane4.setBounds(10, 30, 840, 171);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jButton5.setText("GET DATA");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton5);
        jButton5.setBounds(370, 242, 133, 31);

        jLabel4.setIcon(new javax.swing.ImageIcon("E:\\java project\\Bakery management system\\image\\bake.jpg")); // NOI18N
        jLabel4.setText("jLabel4");
        jPanel4.add(jLabel4);
        jLabel4.setBounds(-6, 4, 870, 440);

        Orders.addTab("Orders", jPanel4);

        getContentPane().add(Orders);
        Orders.setBounds(17, 41, 870, 470);

        jButton6.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        jButton6.setText("LOGOUT");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6);
        jButton6.setBounds(720, 10, 120, 29);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try{
            String sql="select * from Info";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            infotable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
            try{
                rs.close();
                pst.close();

            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try{
            String sql="select * from Contactus";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            msgtable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
            try{
                rs.close();
                pst.close();

            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
       new Optionlogin().setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
         try{
            String sql="select * from OrderInfo";
            pst=con.prepareStatement(sql);
            rs=pst.executeQuery();
            ordertable.setModel(DbUtils.resultSetToTableModel(rs));
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e.getMessage());
        }
        finally{
            try{
                rs.close();
                pst.close();

            }
            catch(Exception e){
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Details.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Details().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane Orders;
    private javax.swing.JTable infotable;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable msgtable;
    private javax.swing.JTable ordertable;
    // End of variables declaration//GEN-END:variables
}
