
import java.sql.*;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author hs247
 */
public class Signup extends javax.swing.JFrame {
       Connection con;
       ResultSet rs;
       PreparedStatement pst;
    
    public Signup() {
        
        initComponents();
         con = dbconnect.ConnecrDB();   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        nameTF = new javax.swing.JTextField();
        emailTF = new javax.swing.JTextField();
        mobileTF = new javax.swing.JTextField();
        pwdPF = new javax.swing.JPasswordField();
        stateCB = new javax.swing.JComboBox<>();
        SubmitBtn = new javax.swing.JButton();
        RestBtn = new javax.swing.JButton();
        CancelBtn = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        useridTF = new javax.swing.JTextField();
        maleRd = new javax.swing.JRadioButton();
        femaleRd = new javax.swing.JRadioButton();
        adrTF = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(900, 530));
        setPreferredSize(new java.awt.Dimension(899, 534));
        setResizable(false);
        setSize(new java.awt.Dimension(900, 530));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Colonna MT", 1, 48)); // NOI18N
        jLabel1.setText("SIGNUP");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(380, 10, 184, 52);

        jLabel2.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel2.setText("NAME");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 120, 70, 30);

        jLabel3.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel3.setText("PASSWORD");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 200, 120, 30);

        jLabel4.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel4.setText("EMAIL");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 161, 70, 30);

        jLabel5.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel5.setText("MOBILE");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 281, 90, 30);

        jLabel6.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel6.setText("GENDER");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 241, 81, 30);

        jLabel9.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel9.setText("STATE");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 330, 70, 30);

        jLabel10.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel10.setText("FULL ADDRESS");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 387, 150, 23);
        getContentPane().add(nameTF);
        nameTF.setBounds(250, 120, 218, 30);
        getContentPane().add(emailTF);
        emailTF.setBounds(250, 160, 218, 30);
        getContentPane().add(mobileTF);
        mobileTF.setBounds(250, 280, 219, 30);

        pwdPF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pwdPFActionPerformed(evt);
            }
        });
        getContentPane().add(pwdPF);
        pwdPF.setBounds(250, 200, 218, 30);

        stateCB.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select--", "Odisha", "New Delhi", "Maharashtra", "Bihar", "West Bengal", "Punjab", "Kerala" }));
        stateCB.setToolTipText("Select");
        stateCB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stateCBActionPerformed(evt);
            }
        });
        getContentPane().add(stateCB);
        stateCB.setBounds(250, 330, 149, 30);

        SubmitBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        SubmitBtn.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        SubmitBtn.setText("SUBMIT");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn);
        SubmitBtn.setBounds(510, 450, 97, 33);

        RestBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        RestBtn.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        RestBtn.setText("RESET");
        RestBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RestBtn);
        RestBtn.setBounds(770, 450, 97, 30);

        CancelBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.darkShadow"));
        CancelBtn.setFont(new java.awt.Font("Perpetua", 1, 18)); // NOI18N
        CancelBtn.setText("CANCEL");
        CancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelBtnActionPerformed(evt);
            }
        });
        getContentPane().add(CancelBtn);
        CancelBtn.setBounds(640, 450, 97, 30);

        jLabel8.setFont(new java.awt.Font("Perpetua Titling MT", 1, 18)); // NOI18N
        jLabel8.setText("USERID");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(30, 90, 71, 23);
        getContentPane().add(useridTF);
        useridTF.setBounds(250, 80, 218, 30);

        maleRd.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        buttonGroup1.add(maleRd);
        maleRd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        maleRd.setText("Male");
        maleRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maleRdActionPerformed(evt);
            }
        });
        getContentPane().add(maleRd);
        maleRd.setBounds(260, 245, 73, 23);

        femaleRd.setBackground(javax.swing.UIManager.getDefaults().getColor("Button.disabledShadow"));
        buttonGroup1.add(femaleRd);
        femaleRd.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        femaleRd.setText("Female");
        femaleRd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                femaleRdActionPerformed(evt);
            }
        });
        getContentPane().add(femaleRd);
        femaleRd.setBounds(373, 245, 63, 23);
        getContentPane().add(adrTF);
        adrTF.setBounds(250, 380, 220, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon("E:\\java project\\Bakery management system\\image\\love_heart_candy_pair-wide.jpg")); // NOI18N
        jLabel11.setText("jLabel11");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(0, 0, 900, 530);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void stateCBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stateCBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stateCBActionPerformed

    private void CancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelBtnActionPerformed
         new Optionlogin().setVisible(true);
         dispose();        
    }//GEN-LAST:event_CancelBtnActionPerformed

    private void RestBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestBtnActionPerformed
         useridTF.setText(" ");
         nameTF.setText(" ");
         emailTF.setText(" ");
         pwdPF.setText(" ");
         maleRd.setSelected(false);
         femaleRd.setSelected(false);
         mobileTF.setText(" ");
         stateCB.setSelectedIndex(0);
         adrTF.setText(" ");
    }//GEN-LAST:event_RestBtnActionPerformed

    private void pwdPFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pwdPFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pwdPFActionPerformed

    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
      String sql = "insert into Info(Userid,Name,Email,Pwd,Gender,Mobile,State,Full_add) values(?,?,?,?,?,?,?,?)";
      try
      {
          pst=con.prepareStatement(sql);
          pst.setString(1,useridTF.getText());
          pst.setString(2,nameTF.getText());
          pst.setString(3,emailTF.getText());
          pst.setString(4,pwdPF.getText());
          maleRd.setActionCommand("Male");
          femaleRd.setActionCommand("Female");
          pst.setString(5,buttonGroup1.getSelection().getActionCommand());
          pst.setString(6,mobileTF.getText());
          pst.setString(7,(String)stateCB.getSelectedItem());
          pst.setString(8,adrTF.getText());
          pst.execute();
          JOptionPane.showMessageDialog(null,"Data insert");
          new Optionlogin().setVisible(true);
          dispose();
        }
      catch(Exception e) {
        JOptionPane.showMessageDialog(null, e);
        }    
      
    }//GEN-LAST:event_SubmitBtnActionPerformed
    
    private void maleRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maleRdActionPerformed
       
    }//GEN-LAST:event_maleRdActionPerformed

    private void femaleRdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_femaleRdActionPerformed
     
    }//GEN-LAST:event_femaleRdActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Signup.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Signup().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancelBtn;
    private javax.swing.JButton RestBtn;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JTextField adrTF;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField emailTF;
    private javax.swing.JRadioButton femaleRd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton maleRd;
    private javax.swing.JTextField mobileTF;
    private javax.swing.JTextField nameTF;
    private javax.swing.JPasswordField pwdPF;
    private javax.swing.JComboBox<String> stateCB;
    private javax.swing.JTextField useridTF;
    // End of variables declaration//GEN-END:variables
}
